#!/usr/bin/env bash

[[ $# < 1 ]] && echo "Specify your branch name" && exit 1

branch_name=$1

git checkout -b "$branch_name" 
git push --set-upstream origin "$branch_name" 
branch_name=$(git rev-parse --abbrev-ref HEAD)
script_dir="./scripts"
[[ -f "$script_dir/$branch_name" ]] && "$script_dir/$branch_name"
[[ -f "$branch_name" ]] && "./$branch_name"
