#!/usr/bin/env bash

[[ $# < 1 ]] && echo "Specify your branch name" && exit 1

branch_name=$1
main_branch_name="development"

git checkout ${main_branch_name}
git push origin --delete "$branch_name"
git branch -D "$branch_name"
