#!/usr/bin/env bash


echo "x" > you
git add you
git commit -m ':)'
echo "x" > will
git add will
git commit -m ':)'
echo "The ASCII code 42 is for the asterisk symbol, being a wildcard for everything" > secret_notes.txt
git add secret_notes.txt

git commit -am ':)'
rm secret_notes.txt
git commit -am ':)'
echo "x" > never
git add never
git commit -m ':)'
echo "x" > find
git add find
git commit -m ':)'
echo "x" > me
git add me
git commit -m ':)'